### ISSUE TITLE
쿠키에 Acces토큰이 안닮기는 이슈

### ISSUE THREAD

**Issue by IHateChem** [coddingyun/DoUSolveThis#26]
## 어떤 버그인가요?
쿠키에 Acces토큰이 안닮기는 이슈

> 어떤 버그인지 간결하게 설명해주세요

/src/pages/login/hooks/api/usePostLogin.js 파일에서 
response.headers.get('GAuth'); -> response.headers.get('Access'); 로 바꾸면 해결될듯 합니당 ~

 
## 어떤 상황에서 발생한 버그인가요?

> Given-When-Then 형식으로 서술해주세요

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

**Comment by coddingyun** [comment]
/api/update/token은 access token이 Gauth로 온다고 스웨거에 적혀있는데, 맞을까요?
